services:
  mypostgres:
    image: postgres
    container_name: mypostgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "ticketing-app"
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - initdb:/var/lib/postgresql/data
  ticketing-app:
    build: .
    container_name: ticketing-app
    ports:
      - "8080:8080"
#    networks:
#      -webnet:
    depends_on:
      - mypostgres
#networks:
#  webnet:
#    driver: bridge
volumes:
  initdb: