version: "3.7"
services:
  mypostgres:
    image: postgres
    container_name: mypostgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "ticketing-app"
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - initdb:/var/lib/postgresql/data

networks:

volumes:
  initbd: